### ISSUE TITLE
Fill out the section "Comparisons with draft-truskovksy"

### ISSUE THREAD

**Issue by ounsworth** [EntrustDatacard/draft-ounsworth-composite-sigs#16]

**Comment by ounsworth** [comment]
@csosto-pk is volunteering to write this, but maybe comment it out in the draft. (since ISARA is expired)

**Comment by ounsworth** [comment]
Tim's opinion is that this might cause more distractions than useful discussion.

**Comment by csosto-pk** [comment]
This is text we can use if necessary and if it is brought up in the WG. Until then let's keep it here only and commented out in the draft. 

The differences between the two drafts are 
- [ISARA](https://datatracker.ietf.org/ipr/search/?draft=draft-truskovsky-lamps-pq-hybrid-x509&submit=draft&rfc=&doctitle=&group=&holder=&iprtitle=&patent)'s IPR declaration is not royalty free. [CableLabs](https://datatracker.ietf.org/ipr/3481/)'s IPR declaration is defensive and royalty free. 
- The composite draft allows for the sig algorithm implementation that happens in software to be plugged in the protocol and be used as blackbox. With draft-truskovsky-lamps-pq-hybrid the protocol implementation needs to take the two parts of the hybrid cert and use them to verify the signature, so it is not like a blackbox. 
- draft-truskovsky-lamps-pq-hybrid has a more straightforward format
- a buggy verifier could check the draft-truskovsky-lamps-pq-hybrid hybrid signature correctly, but check the cert chain by forgetting the PQ parts with draft-truskovsky-lamps-pq-hybrid. With the composite signature the verifier is less prone to mistakenly pass verification if only one key verifies. 
- Other things to consider are the things like simplicity and format, inadvertnt implementation errors, algorithm agility

**Comment by ounsworth** [comment]
Let's skip this, unless it comes up again.
