### ISSUE TITLE
Is "…anywhere that public key or signatures are used" too bold?

### ISSUE THREAD

**Issue by ounsworth** [EntrustDatacard/draft-ounsworth-composite-sigs#18]
In the introduction, it currently says:

> This document is intended for general applicability anywhere that public key structures or digital signatures are used, but where specific design decisions needed to be made, the authors chose the variant that caused the least disruption to existing X.509 certificates, as defined in [RFC5280].

Is the above statement "…anywhere that public key or signatures are used" too bold? Do we need to restrict it with "X500-style" or something? (ie are there styles of public keys and signatures that are not covered by this draft?)

**Comment by csosto-pk** [comment]
Closing this for now, as we seem to be in agreement.
