### ISSUE TITLE
Copy CableLab's IP statements into the section "Intellection Property Considerations"

### ISSUE THREAD

**Issue by ounsworth** [EntrustDatacard/draft-ounsworth-composite-sigs#35]

**Comment by csosto-pk** [comment]
I think this might not be necessary. If CableLabs updates their IPR Declaration https://datatracker.ietf.org/ipr/3481/ to include this new draft we can skip this.

**Comment by ounsworth** [comment]
Max will address this prior to IETF105

**Comment by ounsworth** [comment]
- [ ] Wording to put into the Intellectual Property Considerations section:

> The authors are aware that Massimiliano Pala and CableLabs have applied for
   Intellectual Property Rights around composite key, signatures, and
   certificates.  We have a verbal agreement with Max that this IP will
   be made freely available to the community.

> As of this version of the draft, the authors have reviewed and provided feedback on the March 24, 2019 version of the IPR disclosure, available at <URL>, and are awaiting the posting of an updated version that covers this draft.


 - [ ] Cite RFC8179 in the big list.

**Comment by csosto-pk** [comment]
> * [ ]  Wording to put into the Intellectual Property Considerations section:
> * [ ]  Cite RFC8179 in the big list.

I still don't think it is very common to put IPR related text in IETF draft. The IPR Declaration usually serves as that. If Max updates their IPR Declaration https://datatracker.ietf.org/ipr/3481/ to point to this new draft we can skip this.

**Comment by ounsworth** [comment]
Thanks.

- [ ] Add an EDNOTE to delete this section once Max's IPR Disclosure is properly tagged against this draft in Datatracker.
