### ISSUE TITLE
Suggestion: a CompositeAlg or CompositeSig MUST NOT contain another composite type

### ISSUE THREAD

**Issue by ounsworth** [EntrustDatacard/draft-ounsworth-composite-sigs#38]
Recursion! ..... No! Bad!

**Comment by danvangeest** [comment]
I think SHOULD NOT would be sufficient.  There might be special cases where someone wants to use this recursively, they just have to be aware that it probably won't interoperate with other implementations.

**Comment by ounsworth** [comment]
Related point: an implementation that supports a set of algorithms as components MUST support the same algorithms as top-level algorithms.

**Comment by csosto-pk** [comment]
This is bad IMO. I can't see why someone would use a composite key or sig in a composite key or sig. The point of a composite sig or key is to bundle together multiple of them, I am not sure this makes sense and could be opening cans of worms. I am a proponent of simplicity, unless there is a valid reson.
