### ISSUE TITLE
Suggestion: A signature MAY contain a subset of the algorithms of its corresponding public key, but they MUST still be in the same relative order.

### ISSUE THREAD

**Issue by ounsworth** [EntrustDatacard/draft-ounsworth-composite-sigs#39]
... if a public key contains two algorithms of the same type and only one is present in the signature, this is ambiguous for the verifier.

Ways to handle this:
1. Let it happen, it's the verifier's problem to keep trying public keys until one matches.
. This seems like a footgun both for implementation bugs, and possibly for cryptographic attacks.
1. Signatures MUST contain one component signature for each corresponding public key. This seems unwieldy and would limit a lot of cool applications of composite sigs (like a multi-key entitiy who chooses which key(s) to use based on context)
1. A composite public key MUST NOT contain more than one component key of a given algorithm (ie each algorithmID must appear at most once in a given CompositePublicKey). Therefore by proxy, a composite signature MUST NOT contain more than one component signature of a given algorithm.

there may be a derived requirement here that

**Comment by ounsworth** [comment]
This would need an EDNOTE: to the community to ask whether there are use-cases that would justify the added flexibility / complexity, vs "you must sign with all".

**Comment by danvangeest** [comment]
If fewer signatures are allowed than there are public keys in the issuer, then the issued certificate probably needs an extension indicating how many signatures (and which?) are expected, otherwise an attacker could remove some of the signatures without the verifier knowing.  If the removal is done with knowledge of the verifier's policy this could cause the certificate to be verified at a lower security level than intended.
This extension might even be insufficient because if some of the signatures are weak the attacker could just modify the extension and regenerate only the weak signatures and exclude the strong ones.
The most secure policy would definitely be #2, one signature for each public key.

**Comment by ounsworth** [comment]
Decision: keep it simple; treat a composite key as an atomic object. MUST sign with all component keys.

EDNOTE1: mention that we considered PKI setups where you have a, say 6 key root, and it has issuing CAs that are use-case specific: code-signing CA on Sphincs+, IoT CA on ECSDA+lightweightLattice. However it would require a fairly complex mechanism. We decided that it's not worth it for the first draft, but want public opinions on whether this is a valuable use-case.

EDNOTE2: using the composite cert to combine a signature and a KEM key. See Dan's ticket.

**Comment by csosto-pk** [comment]
> If fewer signatures are allowed than there are public keys in the issuer, then the issued certificate probably needs an extension indicating how many signatures (and which?) are expected, otherwise an attacker could remove some of the signatures without the verifier knowing. If the removal is done with knowledge of the verifier's policy this could cause the certificate to be verified at a lower security level than intended.
> This extension might even be insufficient because if some of the signatures are weak the attacker could just modify the extension and regenerate only the weak signatures and exclude the strong ones.
> The most secure policy would definitely be #2, one signature for each public key.

+1

**Comment by csosto-pk** [comment]
> Decision: keep it simple; treat a composite key as an atomic object. MUST sign with all component keys.
> 
> EDNOTE1: mention that we considered PKI setups where you have a, say 6 key root, and it has issuing CAs that are use-case specific: code-signing CA on Sphincs+, IoT CA on ECSDA+lightweightLattice. However it would require a fairly complex mechanism. We decided that it's not worth it for the first draft, but want public opinions on whether this is a valuable use-case.
> 
> EDNOTE2: using the composite cert to combine a signature and a KEM key. See Dan's ticket.

+1
