### ISSUE TITLE
Signing keys and KEM keys in end-entity certificates

### ISSUE THREAD

**Issue by danvangeest** [EntrustDatacard/draft-ounsworth-composite-sigs#42]
An interesting potential use case for composite public keys is to combine signature keys and KEM keys in end-entity certificates.  Then a single certificate could be used for authentication and encryption.  Is this worth pursuing?

Potential issues:
- (extended) key usage fields.  Simply saying the composite key is valid for signing and encryption may be insufficient if the composite key contains an algorithm such as RSA which can both sign and encrypt, but should not be used to do both with the same key.
- This can probably be abstracted from the protocol layer by the crypto implementation layer, but it would introduce the case where there are N component keys in the composite key but there are < N component signatures in the composite signature passed in the protocol.
- What does it mean to have > 1 KEM keys in a composite public key?  Should they be hybridized [1][2] and if so in what way?  Or should we allow only a single KEM? I (Dan) think restricting it to a single KEM is too restrictive for the same reasons we're allowing multiple signatures for this draft.  > 1 KEM keys could be punted into a separate CompositeKEMKey draft which defines the hybridization mechanism.

[1] https://tools.ietf.org/html/draft-stebila-tls-hybrid-design-00
[2] https://eprint.iacr.org/2018/903.pdf

**Comment by csosto-pk** [comment]
If the uses of these KEMs is for TLS key exchange types of exchanges then using static keys in keyt exchanged is frowned upon in modern years.  They have been considered bad and removed from TLS. 

There might be other public key encryption usecases for this, but we should make sure they are there before we add KEM key specific text in the draft. 

This introduces a new question that we need to explain in the draft. The KU and EKU in the cert, does it apply to all composite keys? I think yes, but we need to state it. I create new issue for it.

**Comment by danvangeest** [comment]
The use case we were thinking of for combining KEMs and signature algorithms in one cert is not for TLS, for the reasons you mention.  It could be used in S/MIME or smart cards for example so a single certificate could be used for authentication and encryption.

**Comment by sfluhrer** [comment]
Composite encryption keys are somewhat nontrivial (it doesn't make sense for each component algorithm to encrypt the plaintext separately; you'll likely end up doing a simple (n, n) secret sharing scheme, and have each algorithm encrypt a share); KEMs are more problematic (how do you combine the separately computed shared secrets to come up with the composite shared secret?  Concatinate?  XOR?  Hash (and if so, which hash)?).  I'd suggest leaving that off to another draft...

**Comment by ounsworth** [comment]
I think this issue is already addressed by @danvangeest 's section `2.4.  Key Usage Bits`.

Can this ticket be closed?

**Comment by ounsworth** [comment]
Also section `7.3.  Composite Encryption and KEMs`.
