### ISSUE TITLE
Cert KU / EKU and composite keys

### ISSUE THREAD

**Issue by csosto-pk** [EntrustDatacard/draft-ounsworth-composite-sigs#43]
The KU and EKU in the cert, does it apply to all composite keys? 
I think yes unless there is a reason it should not. 
We need to state it in the draft.

**Comment by csosto-pk** [comment]
Related to https://github.com/EntrustDatacard/draft-ounsworth-composite-sigs/issues/54

**Comment by ounsworth** [comment]
Serge would like us to remove KEY USAGE (either just the bits, or the whole field?) from the ASN.1, at least for the IETF105 version of the draft. Maybe the way to do that is specify them all so that they're all valid.

Say in text something like

> This draft does not cover encryption, and the component keys single composite key and signatures in a single composite signature must all apply to the same key usage.

**Comment by ounsworth** [comment]
@danvangeest did your changes address this issue?

**Comment by danvangeest** [comment]
@ounsworth yes.  Approve the pull request and this will get closed automatically when I land it :)
