### ISSUE TITLE
To appease TLS-WG, add OIDs for CompositeHash types ?

### ISSUE THREAD

**Issue by ounsworth** [EntrustDatacard/draft-ounsworth-composite-sigs#44]
Define new PublicKey and Signature algs:  

```
 CompositePublicKeyHash ::= {
        HashAlgo    OBJECT IDENTIFIER
        Value           BIT STRING
    }
```
and equivalent Signatures

which contain the hash of a DER-encoded CompositePublicKey object so that TLS can do their "provide data out of band" thing.

**Comment by ounsworth** [comment]
This would be cheap for us to add, and might make ekr happy ... ?

**Comment by danvangeest** [comment]
Would this replace a full CompositePublicKey and CompositeSignature?  Or would it replace one component public key and signature within the public keys/signatures list?

**Comment by csosto-pk** [comment]
Ekr brainstormed this idea to avoid an extra round trip, but I am not sure this is a good idea.  Falcon and Dilithium can offer ~10KB cert chains which is just fine for the initial TCP Congestion Window. We will try to do some testing to prove the point here. 
 
Using a hash and getting the cert later from another TLS extension or a link would mean we either change the TLS 1.3 protocol state machine and security analysis or that we introduce more round trips which defeats the purpose of the idea. 

I propose to not add this until it is brought up in IETF again and we discuss it to see if Ekr can convince us it has merit.

**Comment by sfluhrer** [comment]
Obvious question: why is this idea part of 'composite signatures'?  Wouldn't it be useful even if you were using only a single large public key (e.g. one of the multivariant schemes) or signature (e.g. Sphincs+)?  Should this be its own separate draft?

**Comment by csosto-pk** [comment]
> Obvious question: why is this idea part of 'composite signatures'? Wouldn't it be useful even if you were using only a single large public key (e.g. one of the multivariant schemes) or signature (e.g. Sphincs+)? Should this be its own separate draft?

Yeah, I don't see why it should be here. 

I suggest to close this one.
