### ISSUE TITLE
IETF question: only signature algorithms or KEMs (and others?) as well?

### ISSUE THREAD

**Issue by danvangeest** [EntrustDatacard/draft-ounsworth-composite-sigs#54]
Does the WG want to be able to mix public key capability types in composite objects.  e.g. a composite public key with signature and (encryption, KEM) capabilities.

I don't explicitly mean how to handle the `CERT-KEY-USAGE` field of `PUBLIC-KEY`, although the results of the discussion will inform what we do here.

**Comment by csosto-pk** [comment]
I am afraid that the more changes we are making to how the world looks now the more gaps we are opening and the less likely is for the community to accept, understand and use the standard. 

Today the cert is for one thing. I suggest we keep it that way. It could have multiple keys, but they better be keys used for the same purpose. And I think there should be a MUST to mandate that the keys are for the same thing.

**Comment by ounsworth** [comment]
This is consistent with the current wording of the draft. I'm closing this issue.
