### ISSUE TITLE
Should we submit a talk to the ETSI Quantum-Safe Workshop in Nov?

### ISSUE THREAD

**Issue by ounsworth** [EntrustDatacard/draft-ounsworth-composite-sigs#60]
> The 7th ETSI/IQC Quantum Safe Cryptography Workshop organized by ETSI in partnership with the Institute for Quantum Computing (IQC) and Amazon will take place on 05 to 07 November 2019 at the Amazon Headquarters in Seattle, US.
>
> The Programme Committee is currently calling for presentations and for posters that will populate the technical track. Deadline to submit your proposals is 22 June 2019. Do not miss the deadline! Please check the instructions.

**Comment by sfluhrer** [comment]
I think it’ll make a great deal of sense; I believe ETSI had previously expressed interest in this work…

**Comment by ounsworth** [comment]
Talk abstract submitted!
