### ISSUE TITLE
Add Bibtex reference

### ISSUE THREAD

**Issue by ounsworth** [EntrustDatacard/draft-ounsworth-composite-sigs#71]
Our draft should include a bibtex entry about how to cite it.

See:
https://tools.ietf.org/html/draft-carpenter-rfc-citation-recs-01#section-5.2

**Comment by csosto-pk** [comment]
> Our draft should include a bibtex entry about how to cite it.
> 
> See:
> https://tools.ietf.org/html/draft-carpenter-rfc-citation-recs-01#section-5.2

The bibtex is automatically generated. For our draft it is here https://datatracker.ietf.org/doc/draft-ounsworth-pq-composite-sigs/bibtex/ The link can be found on our draft page https://datatracker.ietf.org/doc/draft-ounsworth-pq-composite-sigs/ 

I think this issue can be closed.

**Comment by ounsworth** [comment]
:O THAT'S AMAZING!!
