### ISSUE TITLE
Should OID in 2.1 be the same as in the 5. ?

### ISSUE THREAD

**Issue by henrydcase** [EntrustDatacard/draft-ounsworth-composite-sigs#76]
If yes, shouldn't we merge 2.1 with 5. ? So that all OIDs are in same palce

**Comment by ounsworth** [comment]
We have not yet asked IANA to assign an official OID to this. My understanding is that usually the IETF / IESG will make the request to IANA for just before your I-D becomes an RFC.

So yes, eventually the plan is to combine sections 2.1 and 5, but for now we're using an OID on the OpenCA OID arc.

**Comment by henrydcase** [comment]
@ounsworth numbers is 2.1 and 5. are different. do you mean the one in 5. is wrong?

**Comment by ounsworth** [comment]
I changed the wording to this, is that clearer?

>The ASN.1 module OID is TBD.  The id-alg-composite OID is to be assigned by IANA.  The authors suggest that IANA assign an OID on the id-pkix arc for this usage:

**Comment by henrydcase** [comment]
perfect! yes, much clearer
